name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
    - run: yarn build
      env:
        CI: true
    - name: Upload build result
      uses: actions/upload-artifact@v1
      with:
        name: plugin
        path: dist
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: plugin
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: plugin/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
